# Kubernetes Service 配置模板
# 用于暴露应用服务

---
# ClusterIP Service - 集群内部访问
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: default
  labels:
    app: myapp
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: myapp
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  - name: metrics
    protocol: TCP
    port: 9090
    targetPort: 9090
  sessionAffinity: None

---
# NodePort Service - 通过节点端口访问
apiVersion: v1
kind: Service
metadata:
  name: myapp-nodeport
  namespace: default
  labels:
    app: myapp
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30080  # 30000-32767 范围

---
# LoadBalancer Service - 通过负载均衡器访问
apiVersion: v1
kind: Service
metadata:
  name: myapp-lb
  namespace: default
  labels:
    app: myapp
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  selector:
    app: myapp
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  - name: https
    protocol: TCP
    port: 443
    targetPort: 8443
  loadBalancerSourceRanges:
  - 0.0.0.0/0
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800

---
# Headless Service - 用于 StatefulSet
apiVersion: v1
kind: Service
metadata:
  name: myapp-headless
  namespace: default
  labels:
    app: myapp
spec:
  clusterIP: None  # Headless
  selector:
    app: myapp
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  publishNotReadyAddresses: true
